[package]
name = "darling-template"
version = "0.1.1"
edition = "2021"
license = "MIT"
readme = "README.md"
authors = ["Violet Iapalucci"]
description = "A template for implementing darling."

[dependencies]
anyhow = "1.0.82"
darling-api = "0.1.2"
